config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      get :listComment
      patch :newComment
    end
  end

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_post, :only => [:show,:edit,:update,:destroy,:newComment]

	def newComment
		puts '---------------------------------'
		puts 'params=='+params.to_s+'......'
		puts '---------------------------------'
		comment=Comment.new(:post_id=>params[:id],:user_id=>current_user.id)
		post=params[:post]
		puts post
		comment.msg=post[:comments][:msg]
		puts comment.msg
		comment.save
		redirect_to post_path(@post)
	end	
	def listComment
		redirect_to post_path(@post)
	end

	def index
		@myuser=current_user
		@posts=Post.page(params[:page]).per(5)
		#@posts=Post.all
	end

	def new
		@post=Post.new
	end
	def create
		@post=Post.new(approve_params)
		@post.user_id=current_user.id
		@post.save
		redirect_to posts_path();		
	end
	def show
		puts '---------------------------------'
		puts 'params=='+params.to_s+'......'
		puts '---------------------------------'
		u=User.where(:id=>@post.user_id)
#		puts u
#		puts u[:email]
#		@owner=u[:email]
		@comments=Comment.where(:post_id=>params[:id])
		#puts @comment[1].msg
#		puts @owner
	end

	def edit
	end
	def update
		@post.update(approve_params)
		redirect_to posts_path();
	end

	def destroy
		@post.destroy
		redirect_to posts_path();
	end
	def find_post
		@post=Post.find(params[:id])
		@myuser=current_user
	end

	private
	def approve_params
		params.require(:post).permit(:topic, :content, :category_id, :user_id, :comments=>[:post_id, :user_id, :msg])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def get_category(x)
      case x
      when 0
        "快報資訊"      
      when 1
        "求物資"
      else
        "求救"
      end
    end
  def init_post_comment(x)
    puts("x.id"+x.id.to_s)
    x.build_comments unless x.comments
    puts(x.comments)
    x
  end
  def short_name(x)
    puts "xxxxxxxxxxxxxxxxxxxxxxx"
    puts x[:email]
    x.email.split("@").first
  end  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ac8Midterm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= f.label :topic, "Topic:" %>
<%= f.text_field :topic%>
<%= f.label :category_id, "Category:"%>
<%= f.select :category_id, [["快報資訊",0],["求物資",1],["求救",2]]%>
<div>
<%= f.label :content, "Content:" %>
<%= f.text_area :content %>
</div>

app/views/posts/edit.html.erb
<h1>edit.html.erb</h1>
<%= form_for @post, :url => post_path(@post) do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "Update", :method=>:patch %>
<% end %>

app/views/posts/index.html.erb
<h1>index.html.erb</h1>
<% if current_user %>
  <%= link_to('log out', destroy_user_session_path, :method => :delete) %> |
          <%= link_to('password', edit_registration_path(:user)) %>
<% else %>
   <%= link_to('regist', new_registration_path(:user)) %> |
          <%= link_to('log in', new_session_path(:user)) %>
<% end %>

<table>
  <thead>
    <tr>
    <th>create at</th><th>category</th><th>author id</th><th>topic</th>
    </tr> 
  </thead>
  <tbody>
  <%@posts.each do |p|%>
  <tr>
    <td>
      <%= p.created_at%>
    </td>  
    <td>
      <%= get_category(p.category_id)%>
    </td>
    <td>
      <%= p.try(:user_id)%>
    </td>
	 <td>  	
	   <%= link_to p.topic, post_path(p) %>
	 </td>
   <% if @myuser.id==p.try(:user_id)%>
	   <td>
      <%= link_to "edit", edit_post_path(p) %>
    </td>
    <td>
      <%= link_to "destroy", post_path(p), :method=>"delete" %>
    </td>
   <%end%>
  </tr>
<%end%>
</tbody>
</table>
<%= paginate @posts %>
<%= link_to "new", new_post_path() %>

app/views/posts/new.html.erb
<h1>new.html.erb</h1>
<%= form_for @post,:url => posts_path do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Create" %>
<% end %>

app/views/posts/show.html.erb
<!-- <h1>show.html.erb</h1> -->
<h1>topic: <%=@post.topic%></h1>
<p>author id:  <%=@post.user_id%></p>
<p>category: 
	<%= get_category(@post.category_id)
	%>
</p>

<hr />
<p>content:</p>
<blockquote>
	<%=simple_format(@post.content)%>
</blockquote>
<h4>Here are comments:</h4>
<table>
	<thead><th>user_id</th><th>statement</th></thead>
	<tbody>
	<%@comments.each do |c|%>
	<tr>
		<td>
			<%= c.user_id
			%>
			<%#=User.where(:id=>c.user_id)%>
		</td>
		<td>
			<%=c.msg%>
		</td>
	</tr>
	<%end%>
	</tbody>
</table>
<!-- add comment field-->
<%= form_for init_post_comment(@post),:url => newComment_post_path(@post) do |f| %>
		<%= f.fields_for :comments do |c| %>
		<p>
			<%= c.label :msg, "msg" %>
			<%= c.text_field :msg%>
		</p>
		<%end%>
    <%= f.submit "add comment"%>
<%end%>

<%= link_to "back to list", posts_path() %>